#!/usr/bin/env bash
#
# This hook adds issue/ticket/version number from branch name to every commit message
#

# Incoming parameters.
COMMIT_MSG_FILE=$1

BRANCH_NAME=$(git symbolic-ref --short HEAD)
BRANCH_NAME2=""

if [ -z "${BRANCH_NAME2-}" ]; then
  echo "[WARNING]: Branch name not found"
  exit 0
fi

echo $BRANCH_NAME

